---
# vars file for mysql

pwd_alias: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
pwd_alias_u: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"

mysql_rpm_list:
  - mysql-community-common-5.7.25-1.el7.x86_64.rpm
  - libaio-0.3.109-13.el7.x86_64.rpm
  - mysql-community-libs-5.7.25-1.el7.x86_64.rpm
  - mysql-community-libs-compat-5.7.25-1.el7.x86_64.rpm
  - perl-Carp-1.26-244.el7.noarch.rpm
  - mysql-community-client-5.7.25-1.el7.x86_64.rpm
  - perl-Exporter-5.68-3.el7.noarch.rpm
  - perl-File-Temp-0.23.01-3.el7.noarch.rpm
  - perl-Encode-2.51-7.el7.x86_64.rpm
  - net-tools-2.0-0.24.20131004git.el7.x86_64.rpm
  - perl-File-Path-2.09-2.el7.noarch.rpm
  - perl-Getopt-Long-2.40-3.el7.noarch.rpm
  - perl-PathTools-3.40-5.el7.x86_64.rpm
  - perl-Filter-1.49-3.el7.x86_64.rpm
  - perl-Pod-Perldoc-3.20-4.el7.noarch.rpm
  - perl-Pod-Simple-3.28-4.el7.noarch.rpm
  - perl-Pod-Usage-1.63-3.el7.noarch.rpm
  - perl-Scalar-List-Utils-1.27-248.el7.x86_64.rpm
  - perl-Pod-Escapes-1.04-294.el7_6.noarch.rpm
  - perl-HTTP-Tiny-0.033-3.el7.noarch.rpm
  - perl-Socket-2.010-4.el7.x86_64.rpm
  - perl-Text-ParseWords-3.29-4.el7.noarch.rpm
  - perl-Storable-2.45-3.el7.x86_64.rpm
  - perl-Time-HiRes-1.9725-3.el7.x86_64.rpm
  - perl-Time-Local-1.2300-2.el7.noarch.rpm
  - perl-constant-1.27-2.el7.noarch.rpm
  - perl-parent-0.225-244.el7.noarch.rpm
  - perl-podlators-2.5.1-3.el7.noarch.rpm
  - perl-threads-1.87-4.el7.x86_64.rpm
  - perl-threads-shared-1.43-6.el7.x86_64.rpm
  - perl-macros-5.16.3-294.el7_6.x86_64.rpm
  - perl-libs-5.16.3-294.el7_6.x86_64.rpm
  - perl-5.16.3-294.el7_6.x86_64.rpm
  - mysql-community-server-5.7.25-1.el7.x86_64.rpm
  - MySQL-python-1.2.5-1.el7.x86_64.rpm

#  - mysql-community-common-5.7.25-1.el7.x86_64.rpm
#  - mysql-community-libs-compat-5.7.25-1.el7.x86_64.rpm
#  - mysql-community-libs-5.7.25-1.el7.x86_64.rpm
#  - mysql-community-server-5.7.25-1.el7.x86_64.rpm
#  - mysql-community-client-5.7.25-1.el7.x86_64.rpm
#  - MySQL-python-1.2.5-1.el7.x86_64.rpm


